name: Build ksud
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      use_cache:
        required: false
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: userspace/ksud
        cache-targets: false

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c

    - name: Install toolchain
      run: rustup target add ${{ inputs.target }}

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Build nsu
      run: |
          if [ "${{ inputs.target }}" == "aarch64-linux-android" ]; then
            abi="arm64-v8a"
            abi2="aarch64"
          elif [ "${{ inputs.target }}" == "x86_64-linux-android" ]; then
            abi="x86_64"
            abi2="x86_64"
          fi
          cd ./userspace/su/
          ndk-build APP_ABI=$abi nsu
          cd ../../
          cp ./userspace/su/obj/local/$abi/nsu ./userspace/ksud/bin/$abi2/su

    - name: Build ksud
      run: cargo ndk --target ${{ inputs.target }} --bindgen build --release 
      working-directory: ./userspace/ksud
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Upload ksud artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksud-${{ inputs.target }}
        path: userspace/ksud/target/**/release/ksud

